services:
  gateway:
    build: ./main-service
    restart: always
    hostname: gateway
    env_file:
      - .env
    ports:
      - ${MAIN_PORT}:${MAIN_PORT}
    networks:
      - backend
    links:
      - mongo
      - ws
      - mysql
    depends_on:
      - mongo
  ws:
    build: ./websocket-service
    restart: always
    hostname: ws
    ports:
      - 80:80
    env_file:
      - .env
    networks:
      - backend
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
      - 33060:33060
    container_name: csrnt-db-backup
    volumes:
      - ./db-backup:/var/lib/mysql
      - ./db-backup-entrypoint/:/docker-entrypoint-initdb.d/
    networks:
      - backend
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    container_name: csrnt-db
    volumes:
      - ./db/:/data/db
    networks:
      - backend
networks:
  backend:
    driver: bridge